### ISSUE TITLE
Change The Kafka Log Retention Hours

### ISSUE THREAD

**Issue by amirmghaemi** [UMD-ARLIS/incubator-flagon-tap#22]
Edit the number of hours kafka keeps a log file before deleting it. Default is 7 days, change to 1 days.

[This may help](https://docs.cloudera.com/HDPDocuments/HDP3/HDP-3.0.1/installing-configuring-kafka/content/log_settings.html#:~:text=The%20default%20value%20is%20168,delete%20or%20compact%20old%20data.&text=The%20number%20of%20hours%20to%20keep%20a%20log%20file%20before%20deleting%20it.)

**Comment by Jyyjy** [comment]
Closing with this commit
https://github.com/UMD-ARLIS/incubator-flagon-tap/commit/7b2e1658892d98b82b399f9070de32c2f41e47f6
