### ISSUE TITLE
Connect Kafka to druid

### ISSUE THREAD

**Issue by Jyyjy** [UMD-ARLIS/incubator-flagon-tap#9]
Write a script to connect kafka to druid. To keep everyone in sync, we should avoid using persistent volumes for the docker images. So everything should be able to get setup and connected via a script. Also, it is ok to ignore the most of the userale log fields when connecting to druid. The timestamp is the only important field; everything else can be added later.

This will most likely be a short python script that posts a json file to druid. Python is not necessary, but it will help with portability.

Resources:
https://druid.apache.org/docs/latest/development/extensions-core/kafka-ingestion.html

**Comment by Jyyjy** [comment]
The current main branch can be connected manually. And my attempt to connect the services via a script is in the `connect` branch. The script does not work, but it is a starting point.

**Comment by rc10house** [comment]
I believe I have a script that works for this. I will email

**Comment by rc10house** [comment]
I believe I have a script that fixes this. I will email you about it @Jyyjy
